#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "clang/ClassExtractor.h"
#include "clang/SyntheticTuParser.h"
#include "generator/CodeGenerator.h"

namespace
{
	void Expect(bool condition, const char* message)
	{
		if (!condition)
		{
			std::cerr << "EXPECTATION FAILED: " << message << '\n';
			std::exit(1);
		}
	}

	void ExpectEqual(std::string_view actual,
					 std::string_view expected,
					 const std::filesystem::path& path)
	{
		if (actual == expected)
		{
			return;
		}

		std::cerr << "generated content mismatch: " << path.generic_string() << '\n';
		std::cerr << "expected:\n" << expected << "\nactual:\n" << actual << '\n';
		std::exit(1);
	}

	[[nodiscard]] std::string ReadText(const std::filesystem::path& path)
	{
		std::ifstream stream(path, std::ios::binary);
		std::ostringstream buffer;
		buffer << stream.rdbuf();
		Expect(stream.good(), "fixture file should be readable");
		return buffer.str();
	}

	[[nodiscard]] mockfakegen::ClassModel ExtractOneClass(const std::filesystem::path& product_dir,
														  std::string_view header_name)
	{
		const auto parse_result = mockfakegen::ParseHeaderWithSyntheticTu({
			.header_path = product_dir / std::filesystem::path(header_name),
			.project_root = product_dir,
		});
		Expect(parse_result.success, "all mocks fixture should parse");

		const mockfakegen::HeaderModel header{
			.absolute_path = parse_result.header.header_path,
			.project_relative_path = parse_result.header.include_spelling,
			.include_spelling = parse_result.header.include_spelling,
			.parsed_by_real_tu = false,
			.parsed_by_synthetic_tu = true,
		};
		const auto extraction =
			mockfakegen::ExtractClassDefinitionsFromAst(*parse_result.ast, header);
		Expect(extraction.classes.size() == 1U, "all mocks header should provide one class");
		return extraction.classes[0];
	}

	[[nodiscard]] bool HasFile(const std::vector<mockfakegen::GeneratedFile>& files,
							   std::string_view relative_path)
	{
		for (const auto& file : files)
		{
			if (file.relative_path.generic_string() == relative_path)
			{
				return true;
			}
		}
		return false;
	}

	void GeneratesDeterministicAllMocks()
	{
		const auto source_dir = std::filesystem::path(MOCKFAKEGEN_SOURCE_DIR);
		const auto product_dir = source_dir / "tests/fixtures/all_mocks/product";
		const auto generated_dir = source_dir / "tests/fixtures/all_mocks/generated";
		std::vector<mockfakegen::ClassModel> classes;
		classes.push_back(ExtractOneClass(product_dir, "Beta.h"));
		classes.push_back(ExtractOneClass(product_dir, "Alpha.h"));

		const auto generated = mockfakegen::GenerateMockFakeProject(classes);
		Expect(HasFile(generated, "AllMocks.h"), "AllMocks.h should be generated by default");
		for (const auto& file : generated)
		{
			const auto path = generated_dir / file.relative_path;
			const auto expected = ReadText(path);
			ExpectEqual(file.content, expected, path);
		}

		const auto generated_without_all_mocks = mockfakegen::GenerateMockFakeProject(
			classes, mockfakegen::ProjectGenerationOptions{.emit_all_mocks = false});
		Expect(!HasFile(generated_without_all_mocks, "AllMocks.h"),
			   "AllMocks.h should be suppressed when disabled");
	}
} // namespace

int main()
{
	GeneratesDeterministicAllMocks();
	return 0;
}
